const dummyTableData = [
  {
    oid: 11,
    newBalance: false,
    balanceChanged: false,
    companyName: 'MOUSE',
    firstName: 'MICKEY',
    lastName: 'MOUSE',
    middleI: null,
    address1: '182636 N. 30TH STREET',
    address2: null,
    city: 'PHOENIX',
    state: 'AZ',
    zip: '85024',
    country: 'USA',
    phoneNumber1: '602-111-2222',
    mobilePhone: '602-111-2222',
    currentBalance: 0.0,
    beginningBalance: 0.0,
    statementBalance: 0.0,
    inactive: false,
    originalCurrentBalance: 0.0,
    notBillable: false
  },
  {
    oid: 22,
    newBalance: false,
    balanceChanged: false,
    companyName: 'MOUSE2',
    firstName: 'MICKEY2',
    lastName: 'MOUSE2',
    middleI: null,
    address1: '182636 N. 30TH STREETs',
    address2: null,
    city: 'PHOENIX',
    state: 'AZ',
    zip: '85024',
    country: 'USA',
    phoneNumber1: '602-111-2222',
    mobilePhone: '602-111-2222',
    currentBalance: 0.0,
    beginningBalance: 0.0,
    statementBalance: 0.0,
    inactive: false,
    originalCurrentBalance: 0.0,
    notBillable: false
  },
  {
    oid: 43,
    newBalance: false,
    balanceChanged: false,
    companyName: 'MOUSE3',
    firstName: 'MICKEY3',
    lastName: 'MOUSE3',
    middleI: null,
    address1: '182636 N. 30TH STREET 3',
    address2: null,
    city: 'PHOENIX',
    state: 'AZ',
    zip: '85024',
    country: 'USA',
    phoneNumber1: '602-111-2222',
    mobilePhone: '602-111-2222',
    currentBalance: 0.0,
    beginningBalance: 0.0,
    statementBalance: 0.0,
    inactive: false,
    originalCurrentBalance: 0.0,
    notBillable: false
  },
  {
    oid: 4,
    newBalance: false,
    balanceChanged: false,
    companyName: 'MOUSE4',
    firstName: 'MICKEY4',
    lastName: 'MOUSE4',
    middleI: null,
    address1: '182636 N. 30TH STREET4',
    address2: null,
    city: 'PHOENIX',
    state: 'AZ',
    zip: '85024',
    country: 'USA',
    phoneNumber1: '602-111-2222',
    mobilePhone: '602-111-2222',
    currentBalance: 0.0,
    beginningBalance: 0.0,
    statementBalance: 0.0,
    inactive: false,
    originalCurrentBalance: 0.0,
    notBillable: false
  }
];
export default dummyTableData;
