const dummyContact = {
  oid: 1,
  phantomPayment: 0.0,
  newBalance: false,
  balanceChanged: false,
  companyName: 'MOUSE',
  firstName: 'MICKEY',
  lastName: 'MOUSE',
  middleI: null,
  address1: '182636 N. 30TH STREET',
  address2: null,
  address3: null,
  city: 'PHOENIX',
  state: 'AZ',
  zip: '85024',
  country: 'USA',
  phoneNumber1: '602-111-2222',
  phoneNumber2: null,
  mobilePhone: '602-111-2222',
  fax: null,
  email: null,
  url: null,
  outlookid: null,
  currentBalance: 0.0,
  beginningBalance: 0.0,
  statementBalance: 0.0,
  other: 0.0,
  inactive: false,
  note: 'this is a test of the notes',
  originalCurrentBalance: 0.0,
  usertag: null,
  ageingAdjustment: null,
  notBillable: false,
  agingCorrection: 0.0
};
export default dummyContact;
