const dummyTableData = [
  {
    oid: 1,
    phantomPayment: 0.0,
    newBalance: false,
    balanceChanged: false,
    companyName: "MOUSE",
    firstName: "MICKEY",
    lastName: "MOUSE",
    middleI: null,
    address1: "182636 N. 30TH STREET",
    address2: null,
    address3: null,
    city: "PHOENIX",
    state: "AZ",
    zip: "85024",
    country: "USA",
    phoneNumber1: "602-111-2222",
    phoneNumber2: null,
    mobilePhone: "602-111-2222",
    fax: null,
    email: null,
    url: null,
    outlookid: null,
    currentBalance: 0.0,
    beginningBalance: 0.0,
    statementBalance: 0.0,
    other: 0.0,
    inactive: false,
    note: "this is a test of the notes",
    originalCurrentBalance: 0.0,
    usertag: null,
    ageingAdjustment: null,
    notBillable: false,
    agingCorrection: 0.0,
  },
  {
    oid: 2,
    phantomPayment: 0.0,
    newBalance: false,
    balanceChanged: false,
    companyName: "MOUSE2",
    firstName: "MICKEY2",
    lastName: "MOUSE2",
    middleI: null,
    address1: "182636 N. 30TH STREETs",
    address2: null,
    address3: null,
    city: "PHOENIX",
    state: "AZ",
    zip: "85024",
    country: "USA",
    phoneNumber1: "602-111-2222",
    phoneNumber2: null,
    mobilePhone: "602-111-2222",
    fax: null,
    email: null,
    url: null,
    outlookid: null,
    currentBalance: 0.0,
    beginningBalance: 0.0,
    statementBalance: 0.0,
    other: 0.0,
    inactive: false,
    note: "this is a test of the notes2",
    originalCurrentBalance: 0.0,
    usertag: null,
    ageingAdjustment: null,
    notBillable: false,
    agingCorrection: 0.0,
  },
  {
    oid: 3,
    phantomPayment: 0.0,
    newBalance: false,
    balanceChanged: false,
    companyName: "MOUSE3",
    firstName: "MICKEY3",
    lastName: "MOUSE3",
    middleI: null,
    address1: "182636 N. 30TH STREET3",
    address2: null,
    address3: null,
    city: "PHOENIX",
    state: "AZ",
    zip: "85024",
    country: "USA",
    phoneNumber1: "602-111-2222",
    phoneNumber2: null,
    mobilePhone: "602-111-2222",
    fax: null,
    email: null,
    url: null,
    outlookid: null,
    currentBalance: 0.0,
    beginningBalance: 0.0,
    statementBalance: 0.0,
    other: 0.0,
    inactive: false,
    note: "this is a test of the notes3",
    originalCurrentBalance: 0.0,
    usertag: null,
    ageingAdjustment: null,
    notBillable: false,
    agingCorrection: 0.0,
  },
  {
    oid: 4,
    phantomPayment: 0.0,
    newBalance: false,
    balanceChanged: false,
    companyName: "MOUSE4",
    firstName: "MICKEY4",
    lastName: "MOUSE4",
    middleI: null,
    address1: "182636 N. 30TH STREET4",
    address2: null,
    address3: null,
    city: "PHOENIX",
    state: "AZ",
    zip: "85024",
    country: "USA",
    phoneNumber1: "602-111-2222",
    phoneNumber2: null,
    mobilePhone: "602-111-2222",
    fax: null,
    email: null,
    url: null,
    outlookid: null,
    currentBalance: 0.0,
    beginningBalance: 0.0,
    statementBalance: 0.0,
    other: 0.0,
    inactive: false,
    note: "this is a test of the notes4",
    originalCurrentBalance: 0.0,
    usertag: null,
    ageingAdjustment: null,
    notBillable: false,
    agingCorrection: 0.0,
  },
];
export default dummyTableData;
