const employees = [
  {
    OID: 1,
    firstName: 'The',
    lastName: 'Foon',
    middleI: null,
    ssn: null,
    employeeNumber: null,
    address1: null,
    address2: null,
    city: null,
    state: null,
    zip: null,
    homePhone: null,
    mobilePhone: null,
    workPhone: null,
    pager: null,
    fax: null,
    otherPhone: null,
    contact: null,
    startDate: null,
    availableDate: null,
    hourlyCost: null,
    inactive: null,
    note: null,
    passwrd: null,
    userType: null,
    username: null
  },
  {
    OID: 2,
    firstName: 'The',
    lastName: 'Bear',
    middleI: null,
    ssn: null,
    employeeNumber: null,
    address1: null,
    address2: null,
    city: null,
    state: null,
    zip: null,
    homePhone: null,
    mobilePhone: null,
    workPhone: null,
    pager: null,
    fax: null,
    otherPhone: null,
    contact: null,
    startDate: null,
    availableDate: null,
    hourlyCost: null,
    inactive: null,
    note: null,
    passwrd: null,
    userType: null,
    username: null
  },
  {
    OID: 3,
    firstName: 'The',
    lastName: 'Beeper',
    middleI: null,
    ssn: null,
    employeeNumber: null,
    address1: null,
    address2: null,
    city: null,
    state: null,
    zip: null,
    homePhone: null,
    mobilePhone: null,
    workPhone: null,
    pager: null,
    fax: null,
    otherPhone: null,
    contact: null,
    startDate: null,
    availableDate: null,
    hourlyCost: null,
    inactive: null,
    note: null,
    passwrd: null,
    userType: null,
    username: null
  }
];

export default employees;
