const employees = [
  {
    OID: 1,
    firstname: 'The',
    lastname: 'Foon',
    middlei: null,
    ssn: null,
    employeenumber: null,
    address1: null,
    address2: null,
    city: null,
    state: null,
    zip: null,
    homephone: null,
    mobilephone: null,
    workphone: null,
    pager: null,
    fax: null,
    otherphone: null,
    contact: null,
    startdate: null,
    availabledate: null,
    hourlycost: null,
    inactive: null,
    note: null,
    passwrd: null,
    usertype: null,
    username: null
  },
  {
    OID: 2,
    firstname: 'The',
    lastname: 'Bear',
    middlei: null,
    ssn: null,
    employeenumber: null,
    address1: null,
    address2: null,
    city: null,
    state: null,
    zip: null,
    homephone: null,
    mobilephone: null,
    workphone: null,
    pager: null,
    fax: null,
    otherphone: null,
    contact: null,
    startdate: null,
    availabledate: null,
    hourlycost: null,
    inactive: null,
    note: null,
    passwrd: null,
    usertype: null,
    username: null
  },
  {
    OID: 3,
    firstname: 'The',
    lastname: 'Beepers',
    middlei: null,
    ssn: null,
    employeenumber: null,
    address1: null,
    address2: null,
    city: null,
    state: null,
    zip: null,
    homephone: null,
    mobilephone: null,
    workphone: null,
    pager: null,
    fax: null,
    otherphone: null,
    contact: null,
    startdate: null,
    availabledate: null,
    hourlycost: null,
    inactive: null,
    note: null,
    passwrd: null,
    usertype: null,
    username: null
  }
];

export default employees;
